package dev.patric.commonlib;

import dev.patric.commonlib.api.CommonRuntime;
import dev.patric.commonlib.api.capability.CapabilityRegistry;
import dev.patric.commonlib.api.capability.CapabilityStatus;
import dev.patric.commonlib.api.capability.StandardCapabilities;
import dev.patric.commonlib.api.adapter.PortBindingService;
import dev.patric.commonlib.api.arena.ArenaInstance;
import dev.patric.commonlib.api.arena.ArenaOpenRequest;
import dev.patric.commonlib.api.arena.ArenaResetContext;
import dev.patric.commonlib.api.arena.ArenaResetResult;
import dev.patric.commonlib.api.arena.ArenaResetStrategy;
import dev.patric.commonlib.api.arena.ArenaService;
import dev.patric.commonlib.api.arena.ArenaStatus;
import dev.patric.commonlib.api.command.CommandModel;
import dev.patric.commonlib.api.command.CommandRegistry;
import dev.patric.commonlib.api.hud.BossBarOpenRequest;
import dev.patric.commonlib.api.hud.BossBarService;
import dev.patric.commonlib.api.hud.BossBarSession;
import dev.patric.commonlib.api.hud.BossBarState;
import dev.patric.commonlib.api.hud.BossBarUpdateResult;
import dev.patric.commonlib.api.hud.HudAudienceCloseReason;
import dev.patric.commonlib.api.hud.HudBarColor;
import dev.patric.commonlib.api.hud.HudBarStyle;
import dev.patric.commonlib.api.hud.HudUpdatePolicy;
import dev.patric.commonlib.api.hud.ScoreboardOpenRequest;
import dev.patric.commonlib.api.hud.ScoreboardSession;
import dev.patric.commonlib.api.hud.ScoreboardSessionService;
import dev.patric.commonlib.api.hud.ScoreboardSnapshot;
import dev.patric.commonlib.api.hud.ScoreboardUpdateResult;
import dev.patric.commonlib.api.gui.GuiCloseReason;
import dev.patric.commonlib.api.gui.GuiDefinition;
import dev.patric.commonlib.api.gui.GuiDefinitionRegistry;
import dev.patric.commonlib.api.gui.GuiDsl;
import dev.patric.commonlib.api.gui.GuiEvent;
import dev.patric.commonlib.api.gui.GuiAction;
import dev.patric.commonlib.api.gui.GuiOpenRequest;
import dev.patric.commonlib.api.gui.GuiSession;
import dev.patric.commonlib.api.gui.GuiSessionService;
import dev.patric.commonlib.api.gui.GuiState;
import dev.patric.commonlib.api.gui.ToggleStateAction;
import dev.patric.commonlib.api.gui.OpenSubMenuAction;
import dev.patric.commonlib.api.gui.BackMenuAction;
import dev.patric.commonlib.api.gui.DialogResponseBinding;
import dev.patric.commonlib.api.dialog.BooleanInputSpec;
import dev.patric.commonlib.api.dialog.CommandTemplateActionSpec;
import dev.patric.commonlib.api.dialog.ConfirmationTypeSpec;
import dev.patric.commonlib.api.dialog.CustomActionSpec;
import dev.patric.commonlib.api.dialog.DialogActionSpec;
import dev.patric.commonlib.api.dialog.DialogAfterAction;
import dev.patric.commonlib.api.dialog.DialogBaseSpec;
import dev.patric.commonlib.api.dialog.DialogBodySpec;
import dev.patric.commonlib.api.dialog.DialogButtonSpec;
import dev.patric.commonlib.api.dialog.DialogCallbacks;
import dev.patric.commonlib.api.dialog.DialogCloseEvent;
import dev.patric.commonlib.api.dialog.DialogCloseReason;
import dev.patric.commonlib.api.dialog.DialogEvent;
import dev.patric.commonlib.api.dialog.DialogEventResult;
import dev.patric.commonlib.api.dialog.DialogInputSpec;
import dev.patric.commonlib.api.dialog.DialogListTypeSpec;
import dev.patric.commonlib.api.dialog.DialogOpenRequest;
import dev.patric.commonlib.api.dialog.DialogResponse;
import dev.patric.commonlib.api.dialog.DialogService;
import dev.patric.commonlib.api.dialog.DialogSession;
import dev.patric.commonlib.api.dialog.DialogSessionStatus;
import dev.patric.commonlib.api.dialog.DialogSubmission;
import dev.patric.commonlib.api.dialog.DialogSubmitEvent;
import dev.patric.commonlib.api.dialog.DialogTemplate;
import dev.patric.commonlib.api.dialog.DialogTemplateRegistry;
import dev.patric.commonlib.api.dialog.DialogTimeoutEvent;
import dev.patric.commonlib.api.dialog.DialogTypeSpec;
import dev.patric.commonlib.api.dialog.ItemBodySpec;
import dev.patric.commonlib.api.dialog.MultiActionTypeSpec;
import dev.patric.commonlib.api.dialog.NoticeTypeSpec;
import dev.patric.commonlib.api.dialog.NumberRangeInputSpec;
import dev.patric.commonlib.api.dialog.PlainMessageBodySpec;
import dev.patric.commonlib.api.dialog.ServerLinksTypeSpec;
import dev.patric.commonlib.api.dialog.SingleOptionEntrySpec;
import dev.patric.commonlib.api.dialog.SingleOptionInputSpec;
import dev.patric.commonlib.api.dialog.StaticClickActionKind;
import dev.patric.commonlib.api.dialog.StaticClickActionSpec;
import dev.patric.commonlib.api.dialog.TextInputSpec;
import dev.patric.commonlib.api.message.FallbackChain;
import dev.patric.commonlib.api.message.MessageRequest;
import dev.patric.commonlib.api.message.PlaceholderResolver;
import dev.patric.commonlib.api.message.PluralRules;
import dev.patric.commonlib.api.module.CommonModule;
import dev.patric.commonlib.api.module.ModulePlanResult;
import dev.patric.commonlib.api.module.ModuleRegistry;
import dev.patric.commonlib.api.module.ModuleState;
import dev.patric.commonlib.api.module.ModuleStatus;
import dev.patric.commonlib.api.persistence.PersistenceRecord;
import dev.patric.commonlib.api.persistence.PersistenceWriteResult;
import dev.patric.commonlib.api.persistence.SchemaMigration;
import dev.patric.commonlib.api.persistence.SchemaMigrationContext;
import dev.patric.commonlib.api.persistence.SchemaMigrationService;
import dev.patric.commonlib.api.persistence.SqlPersistencePort;
import dev.patric.commonlib.api.persistence.YamlPersistencePort;
import dev.patric.commonlib.api.match.DisconnectResult;
import dev.patric.commonlib.api.match.EndReason;
import dev.patric.commonlib.api.match.JoinResult;
import dev.patric.commonlib.api.match.MatchCallbacks;
import dev.patric.commonlib.api.match.MatchCleanup;
import dev.patric.commonlib.api.match.MatchEngineService;
import dev.patric.commonlib.api.match.MatchOpenRequest;
import dev.patric.commonlib.api.match.MatchPolicy;
import dev.patric.commonlib.api.match.MatchSession;
import dev.patric.commonlib.api.match.MatchSessionStatus;
import dev.patric.commonlib.api.match.MatchState;
import dev.patric.commonlib.api.match.MatchTimingPolicy;
import dev.patric.commonlib.api.match.MatchTransitionResult;
import dev.patric.commonlib.api.match.RejoinPolicy;
import dev.patric.commonlib.api.match.RejoinResult;
import dev.patric.commonlib.api.port.ArenaResetPort;
import dev.patric.commonlib.api.port.BossBarPort;
import dev.patric.commonlib.api.port.ClaimsPort;
import dev.patric.commonlib.api.port.CommandPort;
import dev.patric.commonlib.api.port.GuiPort;
import dev.patric.commonlib.api.port.HologramPort;
import dev.patric.commonlib.api.port.MetricsPort;
import dev.patric.commonlib.api.port.NpcPort;
import dev.patric.commonlib.api.port.PacketPort;
import dev.patric.commonlib.api.port.ScoreboardPort;
import dev.patric.commonlib.api.port.SchematicPort;
import dev.patric.commonlib.api.packet.PacketDirection;
import dev.patric.commonlib.api.packet.PacketEnvelope;
import dev.patric.commonlib.api.packet.PacketListenerHandle;
import dev.patric.commonlib.api.packet.PacketListenerOptions;
import dev.patric.commonlib.api.packet.PacketListenerPriority;
import dev.patric.commonlib.api.port.noop.NoopArenaResetPort;
import dev.patric.commonlib.api.port.noop.NoopBossBarPort;
import dev.patric.commonlib.api.port.noop.NoopClaimsPort;
import dev.patric.commonlib.api.port.noop.NoopCommandPort;
import dev.patric.commonlib.api.port.noop.NoopGuiPort;
import dev.patric.commonlib.api.port.noop.NoopHologramPort;
import dev.patric.commonlib.api.port.noop.NoopMetricsPort;
import dev.patric.commonlib.api.port.noop.NoopNpcPort;
import dev.patric.commonlib.api.port.noop.NoopPacketPort;
import dev.patric.commonlib.api.port.noop.NoopSchematicPort;
import dev.patric.commonlib.api.port.noop.NoopScoreboardPort;
import dev.patric.commonlib.api.port.options.PasteOptions;
import dev.patric.commonlib.api.team.FriendlyFirePolicy;
import dev.patric.commonlib.api.team.PartyActionResult;
import dev.patric.commonlib.api.team.PartyService;
import dev.patric.commonlib.api.team.PartySnapshot;
import dev.patric.commonlib.api.team.PartyStatus;
import dev.patric.commonlib.api.team.TeamAssignmentResult;
import dev.patric.commonlib.api.team.TeamDefinition;
import dev.patric.commonlib.api.team.TeamService;
import dev.patric.commonlib.api.team.TeamSnapshot;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import static org.junit.jupiter.api.Assertions.assertNotNull;

class CommonLibSmokeTest {

    @Test
    void classesAreLoadableAndVersionIsPresent() {
        assertNotNull(CommonLib.version());
        assertDoesNotThrow(() -> Class.forName(CommonRuntime.class.getName()));
        assertDoesNotThrow(() -> Class.forName(CommandPort.class.getName()));
        assertDoesNotThrow(() -> Class.forName(GuiPort.class.getName()));
        assertDoesNotThrow(() -> Class.forName(ScoreboardPort.class.getName()));
        assertDoesNotThrow(() -> Class.forName(BossBarPort.class.getName()));
        assertDoesNotThrow(() -> Class.forName(ArenaResetPort.class.getName()));
        assertDoesNotThrow(() -> Class.forName(MetricsPort.class.getName()));
        assertDoesNotThrow(() -> Class.forName(PacketPort.class.getName()));
        assertDoesNotThrow(() -> Class.forName(ArenaService.class.getName()));
        assertDoesNotThrow(() -> Class.forName(ArenaInstance.class.getName()));
        assertDoesNotThrow(() -> Class.forName(ArenaOpenRequest.class.getName()));
        assertDoesNotThrow(() -> Class.forName(ArenaResetContext.class.getName()));
        assertDoesNotThrow(() -> Class.forName(ArenaResetResult.class.getName()));
        assertDoesNotThrow(() -> Class.forName(ArenaResetStrategy.class.getName()));
        assertDoesNotThrow(() -> Class.forName(ArenaStatus.class.getName()));
        assertDoesNotThrow(() -> Class.forName(NpcPort.class.getName()));
        assertDoesNotThrow(() -> Class.forName(HologramPort.class.getName()));
        assertDoesNotThrow(() -> Class.forName(ClaimsPort.class.getName()));
        assertDoesNotThrow(() -> Class.forName(SchematicPort.class.getName()));
        assertDoesNotThrow(() -> Class.forName(PasteOptions.class.getName()));
        assertDoesNotThrow(() -> Class.forName(PacketDirection.class.getName()));
        assertDoesNotThrow(() -> Class.forName(PacketListenerPriority.class.getName()));
        assertDoesNotThrow(() -> Class.forName(PacketListenerOptions.class.getName()));
        assertDoesNotThrow(() -> Class.forName(PacketEnvelope.class.getName()));
        assertDoesNotThrow(() -> Class.forName(PacketListenerHandle.class.getName()));
        assertDoesNotThrow(() -> Class.forName(CapabilityRegistry.class.getName()));
        assertDoesNotThrow(() -> Class.forName(CapabilityStatus.class.getName()));
        assertDoesNotThrow(() -> Class.forName(StandardCapabilities.class.getName()));
        assertDoesNotThrow(() -> Class.forName(PortBindingService.class.getName()));
        assertDoesNotThrow(() -> Class.forName(CommandModel.class.getName()));
        assertDoesNotThrow(() -> Class.forName(CommandRegistry.class.getName()));
        assertDoesNotThrow(() -> Class.forName(MessageRequest.class.getName()));
        assertDoesNotThrow(() -> Class.forName(PlaceholderResolver.class.getName()));
        assertDoesNotThrow(() -> Class.forName(FallbackChain.class.getName()));
        assertDoesNotThrow(() -> Class.forName(PluralRules.class.getName()));
        assertDoesNotThrow(() -> Class.forName(GuiState.class.getName()));
        assertDoesNotThrow(() -> Class.forName(GuiDefinition.class.getName()));
        assertDoesNotThrow(() -> Class.forName(GuiDefinitionRegistry.class.getName()));
        assertDoesNotThrow(() -> Class.forName(GuiDsl.class.getName()));
        assertDoesNotThrow(() -> Class.forName(GuiAction.class.getName()));
        assertDoesNotThrow(() -> Class.forName(ToggleStateAction.class.getName()));
        assertDoesNotThrow(() -> Class.forName(OpenSubMenuAction.class.getName()));
        assertDoesNotThrow(() -> Class.forName(BackMenuAction.class.getName()));
        assertDoesNotThrow(() -> Class.forName(DialogResponseBinding.class.getName()));
        assertDoesNotThrow(() -> Class.forName(GuiOpenRequest.class.getName()));
        assertDoesNotThrow(() -> Class.forName(GuiSession.class.getName()));
        assertDoesNotThrow(() -> Class.forName(GuiEvent.class.getName()));
        assertDoesNotThrow(() -> Class.forName(GuiCloseReason.class.getName()));
        assertDoesNotThrow(() -> Class.forName(GuiSessionService.class.getName()));
        assertDoesNotThrow(() -> Class.forName(DialogService.class.getName()));
        assertDoesNotThrow(() -> Class.forName(DialogTemplateRegistry.class.getName()));
        assertDoesNotThrow(() -> Class.forName(DialogResponse.class.getName()));
        assertDoesNotThrow(() -> Class.forName(DialogCallbacks.class.getName()));
        assertDoesNotThrow(() -> Class.forName(DialogOpenRequest.class.getName()));
        assertDoesNotThrow(() -> Class.forName(DialogSession.class.getName()));
        assertDoesNotThrow(() -> Class.forName(DialogSessionStatus.class.getName()));
        assertDoesNotThrow(() -> Class.forName(DialogCloseReason.class.getName()));
        assertDoesNotThrow(() -> Class.forName(DialogEventResult.class.getName()));
        assertDoesNotThrow(() -> Class.forName(DialogEvent.class.getName()));
        assertDoesNotThrow(() -> Class.forName(DialogSubmitEvent.class.getName()));
        assertDoesNotThrow(() -> Class.forName(DialogTimeoutEvent.class.getName()));
        assertDoesNotThrow(() -> Class.forName(DialogCloseEvent.class.getName()));
        assertDoesNotThrow(() -> Class.forName(DialogSubmission.class.getName()));
        assertDoesNotThrow(() -> Class.forName(DialogTemplate.class.getName()));
        assertDoesNotThrow(() -> Class.forName(DialogBaseSpec.class.getName()));
        assertDoesNotThrow(() -> Class.forName(DialogAfterAction.class.getName()));
        assertDoesNotThrow(() -> Class.forName(DialogBodySpec.class.getName()));
        assertDoesNotThrow(() -> Class.forName(PlainMessageBodySpec.class.getName()));
        assertDoesNotThrow(() -> Class.forName(ItemBodySpec.class.getName()));
        assertDoesNotThrow(() -> Class.forName(DialogInputSpec.class.getName()));
        assertDoesNotThrow(() -> Class.forName(TextInputSpec.class.getName()));
        assertDoesNotThrow(() -> Class.forName(BooleanInputSpec.class.getName()));
        assertDoesNotThrow(() -> Class.forName(NumberRangeInputSpec.class.getName()));
        assertDoesNotThrow(() -> Class.forName(SingleOptionInputSpec.class.getName()));
        assertDoesNotThrow(() -> Class.forName(SingleOptionEntrySpec.class.getName()));
        assertDoesNotThrow(() -> Class.forName(DialogTypeSpec.class.getName()));
        assertDoesNotThrow(() -> Class.forName(ConfirmationTypeSpec.class.getName()));
        assertDoesNotThrow(() -> Class.forName(NoticeTypeSpec.class.getName()));
        assertDoesNotThrow(() -> Class.forName(MultiActionTypeSpec.class.getName()));
        assertDoesNotThrow(() -> Class.forName(DialogListTypeSpec.class.getName()));
        assertDoesNotThrow(() -> Class.forName(ServerLinksTypeSpec.class.getName()));
        assertDoesNotThrow(() -> Class.forName(DialogButtonSpec.class.getName()));
        assertDoesNotThrow(() -> Class.forName(DialogActionSpec.class.getName()));
        assertDoesNotThrow(() -> Class.forName(CommandTemplateActionSpec.class.getName()));
        assertDoesNotThrow(() -> Class.forName(StaticClickActionKind.class.getName()));
        assertDoesNotThrow(() -> Class.forName(StaticClickActionSpec.class.getName()));
        assertDoesNotThrow(() -> Class.forName(CustomActionSpec.class.getName()));
        assertDoesNotThrow(() -> Class.forName(HudAudienceCloseReason.class.getName()));
        assertDoesNotThrow(() -> Class.forName(HudUpdatePolicy.class.getName()));
        assertDoesNotThrow(() -> Class.forName(ScoreboardSnapshot.class.getName()));
        assertDoesNotThrow(() -> Class.forName(ScoreboardOpenRequest.class.getName()));
        assertDoesNotThrow(() -> Class.forName(ScoreboardSession.class.getName()));
        assertDoesNotThrow(() -> Class.forName(ScoreboardUpdateResult.class.getName()));
        assertDoesNotThrow(() -> Class.forName(ScoreboardSessionService.class.getName()));
        assertDoesNotThrow(() -> Class.forName(HudBarColor.class.getName()));
        assertDoesNotThrow(() -> Class.forName(HudBarStyle.class.getName()));
        assertDoesNotThrow(() -> Class.forName(BossBarState.class.getName()));
        assertDoesNotThrow(() -> Class.forName(BossBarOpenRequest.class.getName()));
        assertDoesNotThrow(() -> Class.forName(BossBarSession.class.getName()));
        assertDoesNotThrow(() -> Class.forName(BossBarUpdateResult.class.getName()));
        assertDoesNotThrow(() -> Class.forName(BossBarService.class.getName()));
        assertDoesNotThrow(() -> Class.forName(MatchState.class.getName()));
        assertDoesNotThrow(() -> Class.forName(EndReason.class.getName()));
        assertDoesNotThrow(() -> Class.forName(MatchSessionStatus.class.getName()));
        assertDoesNotThrow(() -> Class.forName(MatchTimingPolicy.class.getName()));
        assertDoesNotThrow(() -> Class.forName(RejoinPolicy.class.getName()));
        assertDoesNotThrow(() -> Class.forName(MatchPolicy.class.getName()));
        assertDoesNotThrow(() -> Class.forName(MatchOpenRequest.class.getName()));
        assertDoesNotThrow(() -> Class.forName(MatchSession.class.getName()));
        assertDoesNotThrow(() -> Class.forName(MatchTransitionResult.class.getName()));
        assertDoesNotThrow(() -> Class.forName(JoinResult.class.getName()));
        assertDoesNotThrow(() -> Class.forName(DisconnectResult.class.getName()));
        assertDoesNotThrow(() -> Class.forName(RejoinResult.class.getName()));
        assertDoesNotThrow(() -> Class.forName(MatchCallbacks.class.getName()));
        assertDoesNotThrow(() -> Class.forName(MatchCleanup.class.getName()));
        assertDoesNotThrow(() -> Class.forName(MatchEngineService.class.getName()));
        assertDoesNotThrow(() -> Class.forName(CommonModule.class.getName()));
        assertDoesNotThrow(() -> Class.forName(ModuleState.class.getName()));
        assertDoesNotThrow(() -> Class.forName(ModuleStatus.class.getName()));
        assertDoesNotThrow(() -> Class.forName(ModuleRegistry.class.getName()));
        assertDoesNotThrow(() -> Class.forName(ModulePlanResult.class.getName()));
        assertDoesNotThrow(() -> Class.forName(FriendlyFirePolicy.class.getName()));
        assertDoesNotThrow(() -> Class.forName(TeamDefinition.class.getName()));
        assertDoesNotThrow(() -> Class.forName(TeamAssignmentResult.class.getName()));
        assertDoesNotThrow(() -> Class.forName(TeamSnapshot.class.getName()));
        assertDoesNotThrow(() -> Class.forName(TeamService.class.getName()));
        assertDoesNotThrow(() -> Class.forName(PartyStatus.class.getName()));
        assertDoesNotThrow(() -> Class.forName(PartyActionResult.class.getName()));
        assertDoesNotThrow(() -> Class.forName(PartySnapshot.class.getName()));
        assertDoesNotThrow(() -> Class.forName(PartyService.class.getName()));
        assertDoesNotThrow(() -> Class.forName(PersistenceRecord.class.getName()));
        assertDoesNotThrow(() -> Class.forName(PersistenceWriteResult.class.getName()));
        assertDoesNotThrow(() -> Class.forName(YamlPersistencePort.class.getName()));
        assertDoesNotThrow(() -> Class.forName(SqlPersistencePort.class.getName()));
        assertDoesNotThrow(() -> Class.forName(SchemaMigration.class.getName()));
        assertDoesNotThrow(() -> Class.forName(SchemaMigrationContext.class.getName()));
        assertDoesNotThrow(() -> Class.forName(SchemaMigrationService.class.getName()));
        assertDoesNotThrow(() -> Class.forName(NoopNpcPort.class.getName()));
        assertDoesNotThrow(() -> Class.forName(NoopHologramPort.class.getName()));
        assertDoesNotThrow(() -> Class.forName(NoopClaimsPort.class.getName()));
        assertDoesNotThrow(() -> Class.forName(NoopSchematicPort.class.getName()));
        assertDoesNotThrow(() -> Class.forName(NoopCommandPort.class.getName()));
        assertDoesNotThrow(() -> Class.forName(NoopGuiPort.class.getName()));
        assertDoesNotThrow(() -> Class.forName(NoopScoreboardPort.class.getName()));
        assertDoesNotThrow(() -> Class.forName(NoopBossBarPort.class.getName()));
        assertDoesNotThrow(() -> Class.forName(NoopArenaResetPort.class.getName()));
        assertDoesNotThrow(() -> Class.forName(NoopMetricsPort.class.getName()));
        assertDoesNotThrow(() -> Class.forName(NoopPacketPort.class.getName()));
    }
}
